algoritmo "crescente"
// Função :
// Autor :
// Data : 15/06/2020
// Seção de Declarações 
var
   x, y : inteiro
inicio
      escreval("Digite dois núemros: ")
      leia(x)
      leia(y)
      
      enquanto (x <> y) faca
          se (x < y) entao
             escreval("CRESCENTE!")
          senao
               escreval("DECRESCENTE!")
          fimse
          
          escreval("Digite dois números: ")
          leia(x)
          leia(y)
      fimenquanto
fimalgoritmo
